name: Publish Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Corrected path to lowercase "server"
      - name: Build and push server image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/quickai-server:latest

      # Corrected path to uppercase "Client"
      - name: Build and push client image
        uses: docker/build-push-action@v5
        with:
          context: ./Client
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/quickai-client:latest
